// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// kfs_ewma_parameters
Rcpp::List kfs_ewma_parameters(arma::mat y, arma::mat x, int p, bool constant, arma::mat Q0, arma::mat beta0, arma::mat R0, arma::mat V0, arma::mat lambda0, arma::mat W0, double kappaQ, double kappaR, double kappaV, double kappaW);
RcppExport SEXP _fincond_kfs_ewma_parameters(SEXP ySEXP, SEXP xSEXP, SEXP pSEXP, SEXP constantSEXP, SEXP Q0SEXP, SEXP beta0SEXP, SEXP R0SEXP, SEXP V0SEXP, SEXP lambda0SEXP, SEXP W0SEXP, SEXP kappaQSEXP, SEXP kappaRSEXP, SEXP kappaVSEXP, SEXP kappaWSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< bool >::type constant(constantSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q0(Q0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type R0(R0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type V0(V0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lambda0(lambda0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W0(W0SEXP);
    Rcpp::traits::input_parameter< double >::type kappaQ(kappaQSEXP);
    Rcpp::traits::input_parameter< double >::type kappaR(kappaRSEXP);
    Rcpp::traits::input_parameter< double >::type kappaV(kappaVSEXP);
    Rcpp::traits::input_parameter< double >::type kappaW(kappaWSEXP);
    rcpp_result_gen = Rcpp::wrap(kfs_ewma_parameters(y, x, p, constant, Q0, beta0, R0, V0, lambda0, W0, kappaQ, kappaR, kappaV, kappaW));
    return rcpp_result_gen;
END_RCPP
}
// kk_favar
Rcpp::List kk_favar(Rcpp::List object);
RcppExport SEXP _fincond_kk_favar(SEXP objectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    rcpp_result_gen = Rcpp::wrap(kk_favar(object));
    return rcpp_result_gen;
END_RCPP
}
// pca
Rcpp::List pca(arma::mat x);
RcppExport SEXP _fincond_pca(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(pca(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fincond_kfs_ewma_parameters", (DL_FUNC) &_fincond_kfs_ewma_parameters, 14},
    {"_fincond_kk_favar", (DL_FUNC) &_fincond_kk_favar, 1},
    {"_fincond_pca", (DL_FUNC) &_fincond_pca, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_fincond(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
