# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' KPS EWMA algorithm
#' 
#' Implementation of something
#' 
#' @param y variables of the measurement equation
#' @param x variable of the factor equation
#' @param p integer of the lag order of the VAR model
#' @param const logical specifying whether a constant should be included in the VAR model
#' @param Q0 matrix of the initital values
#' @param beta0 vector of initial values
#' @param R0 matrix of the initital values
#' @param V0 matrix of the initital values
#' @param lambda0 matrix of initial values
#' @param W0 matrix of the initital values
#' @param kappaQ forgetting factor
#' @param kappaR decay factor
#' @param kappaV forgetting factor
#' @param kappaW decay factor
#' 
#' @details Produces a draw
#'
#' @noRd
#' 
kfs_ewma_parameters <- function(y, x, p, constant, Q0, beta0, R0, V0, lambda0, W0, kappaQ, kappaR, kappaV, kappaW) {
    .Call(`_fincond_kfs_ewma_parameters`, y, x, p, constant, Q0, beta0, R0, V0, lambda0, W0, kappaQ, kappaR, kappaV, kappaW)
}

#' Koop and Korobilis (2014) TVP-FAVAR
#'
#' The estimator behind \code{\link{add_posterior_coefficients.fcimodel}}. Not
#' exported: it takes the model object apart itself and assumes
#' \code{\link{add_priors.fcimodel}} has filled it in.
#'
#' @param object an object of class \code{"fcimodel"}.
#'
#' @noRd
.kk_favar <- function(object) {
    .Call(`_fincond_kk_favar`, object)
}

#' KPS EWMA algorithm
#' 
#' Implementation of something
#' 
#' @param x a time series.
#' 
#' @details Produces a draw
#'
#' @noRd
#' 
pca <- function(x) {
    .Call(`_fincond_pca`, x)
}

